/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 68429bcfd7bb4c7f8f2cfc182c641410)
interface __BaseEnv_CloudflareEnv {
	UPLOADS: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	MICROCMS_SERVICE_DOMAIN: string;
	MICROCMS_API_KEY: string;
	NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	LINE_CLIENT_ID: string;
	LINE_CLIENT_SECRET: string;
	LINE_CHANNEL_SECRET: string;
	LINE_CHANNEL_ACCESS_TOKEN: string;
	ANTHROPIC_API_KEY: string;
	LINE_ORDER_SPREADSHEET_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MICROCMS_SERVICE_DOMAIN" | "MICROCMS_API_KEY" | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "NEXTAUTH_SECRET" | "NEXTAUTH_URL" | "LINE_CLIENT_ID" | "LINE_CLIENT_SECRET" | "LINE_CHANNEL_SECRET" | "LINE_CHANNEL_ACCESS_TOKEN" | "ANTHROPIC_API_KEY" | "LINE_ORDER_SPREADSHEET_ID">> {}
}
